
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Priyanka Garg  ## put your name
title: 'Senior Business Accountant'  ## your title
location: Greater Noida, IN


## Social Profiles
facebook: https://www.facebook.com/priyanka.garg.71271466 ## your facebook account url
twitter: http://www.twitter.com/priyankagarg12394  ## your twitter account url
linkedin: https://www.linkedin.com/in/priyankagarg12394  ## your linkedin account url



# Update all the sections by editing the files inside _includes folder.
